### ISSUE TITLE
Create UI Mockup for Item Detail

### ISSUE THREAD

**Issue by luigibesani** [DnD-Montreal/session-tome#125]
Create design mockups for displaying item details.

UI Interactive Mockup link:

- [Exploring a Magic Item](https://www.figma.com/proto/5uF4bHcHFTm13iMyrBzMt0/Designs-and-Mockups?node-id=12%3A6&scaling=min-zoom&starting-point-node-id=593%3A24170&show-proto-sidebar=1)

**Comment by AnnieTran13** [comment]
Will the description have a basic summary of the item and when it expands it will "continue" the description or do we have to expand it in order to have any information on description? I think that if I clicked on an item from a list, I would like to see all its information right away without having to click again to get more information and then clicking again to close the description. 
Here is a specific situation: while I'm reading I forget what item I'm reading the description of (or I forget what rarity or tier it is) and so, I am required to close the description, reopen it again and try to find where I left off. Assuming we have a long description that requires scrolling, finding where I left off would be hard because reopening it will reset it and you start again at the top of the card.
In my personal experience, if the description was fully in the same page, I would highlight the text (select a big chunk) so that it's visible where I left off, scroll up to somewhere else on the page and then back to my selected text. This isn't possible if the description is in an expandable card.
Here is my proposed change (if you guys agree): we remove the expanding and leave the whole description on the same page. Since it can be very long, it might push the button too far down the page and so I suggest the buttons go at the very top so they are always visible no matter the length of the content.

**Comment by m-triassi** [comment]
i'd actually agree with Annie here; this is a detail page for a single item, so there isn't really a purpose to hiding the description in an expansion box; putting the buttons above the description box and then letting the description be what ever length it is sounds like a good solution to me.

As a side note, i don't think the export button would be useful here. Exporting data is mostly for when a user wants to take their entire character to a different platform

**Comment by pascwhale** [comment]
Thanks for the feedback everybody. Could you click on the same link and tell me what you think?

**Comment by AnnieTran13** [comment]
Thanks for making the change! Sorry if I commented too much or if I sounded too harsh... I think it looks really good! Nice job :)

**Comment by pascwhale** [comment]
Not at all, I guess I can close this issue now.
