### ISSUE TITLE
Accept: Manage characters

### ISSUE THREAD

**Issue by m-triassi** [DnD-Montreal/session-tome#159]
## Description
Acceptance Test for #32
Ability to create, read, update, and delete characters belonging to a particular user.

[UAT Environment](https://session-tome.triassi.ca) for executing the acceptance flow

## Acceptance flow
1. User Logs in
2. User clicks the "Create" button and fills the form
3. User Clicks accept and observes their character on the index 
4. User clicks the edit icon, and makes some changes in the form
5. User clicks accept and observes the new values have appeared on their character
6. User clicks on the delete icon for their newly created character
7. User confirms their action in the deletion modal and observes the character is gone.

**Comment by DndMtl** [comment]
It was super easy to create a character and they showed up! I was able to edit and delete them with ease. Fantastic!

Some Suggestions: 
- Would be helpful if there was a dropdown feature for race/class/faction as to avoid typos for better organizing. 
- Will there be subclasses added? It would be great to have that eventually
- The scroll for the level/downtime isn't ideal since a slight movement and suddenly I'm level 20 with 4000000 downtime. I'd remove this and make it a manual entry for both.
- Sort would be helpful if the most recent characters added were first instead of on the second page
On the character page EDIT > UPDATE > would be ideal if it went right to SAVE instead of CONTINUE. Save a click


-Kate Ruscito
