### ISSUE TITLE
Campaign Index Screen

### ISSUE THREAD

**Issue by m-triassi** [DnD-Montreal/session-tome#371]
## Description

Users should be able to see a list of all the campaigns they are registered in. This can be a table that lists the title of the campaign as well as the character, if any, they are using in the campaign. They should also be able to see the details of the campaign. This could include the entries that were generated as part of the campaign, among other things like campaign title, characters, etc...

## Possible Implementation

N/a

## Out of scope

N/a

## Requirements / Restrictions

N/a

## Mockups
[Campaign Index](https://www.figma.com/proto/5uF4bHcHFTm13iMyrBzMt0/Designs-and-Mockups?node-id=12%3A6&scaling=min-zoom&starting-point-node-id=1210%3A32138&show-proto-sidebar=1)

**Comment by pascwhale** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Session-Tome-613674a263226c0015d44c06/issues/DnD-Montreal/session-tome/371?planning-poker) with ZenHub @AnnieTran13 @luigibesani @willyyhuang

**Comment by willyyhuang** [comment]
I took a look at the campaign index page, here are some feedbacks:
- Since you have to click on the join button to generate the url to join a campaign i believe, is it better to add the url directly as one of the column, and let user able to click to copy url?
- The page looks pretty empty, maybe we can show more data in the table view? I am not sure what fields are related to campaign exactly but if there are not a lot of fields, I don't think we need a detail view
