### ISSUE TITLE
Replace Cypress Login Calls with Laravel Login

### ISSUE THREAD

**Issue by pascwhale** [DnD-Montreal/session-tome#539]
## Description

Speed up the process of logging into the default test user's account during Cypress tests.

## Possible Implementation

Replace login action for Cypress tests with a simple `cy.login({id: 1})` call to log into the default test user without having to use the UI.

**Comment by willyyhuang** [comment]
Not sure why this is needed? using laravel's function to login to a default test user means that the seeder has to be ran, which already slows down every single test case we have

**Comment by pascwhale** [comment]
This will only be added where the seeder is already needed. It takes less than a second to login using this call, while it take a few seconds to click on the right UI buttons to input the default test user's credentials. This task is not necessary but it will shave off a few seconds every time the old login method is used.

**Comment by willyyhuang** [comment]
https://katalon.com/resources-center/blog/end-to-end-e2e-testing#:~:text=End%2Dto%2Dend%20testing%20is,pieces%20work%20together%20as%20expected.

the reason why I'm pointing this out is because e2e testing has the purpose of testing the integrated application flow, what you will be doing in this issue by replacing UI clicks to request API calls will just result in this coverage of the test to become solely a backend testing, which is very redundant in my opinion because backend unit tests already handle those very well.

**Comment by pascwhale** [comment]
Again, it's just to save some time on the Cypress pipeline. The login using the UI is tested on its own, therefore I would argue that the scope of the other tests don't really include the login. The other parts of the test will remain the same and  still count as E2E tests.

**Comment by pascwhale** [comment]
We can discuss this more when I open my PR. It's not that hard of a task anyway.

**Comment by pascwhale** [comment]
This didn't really improve the Cypress pipeline duration, so I don't think it's a good idea to merge these changes.
